### ISSUE TITLE
Becoming a collaborator

### ISSUE THREAD

**Issue by KeeJef** [flathub/network.loki.Session#81]
Hey guys 

I'm the CTO at Session was wondering if i could get access on this repo so i can cosign any releases which go out, we want to add the flatpak to our website, but without access i can't.

Thanks

**Comment by GeopJr** [comment]
cc: @barthalion

**Comment by KeeJef** [comment]
Hmmm verification requires a page at loki.network, we no longer use this domain, probably best to point towards https://getsession.org

**Comment by GeopJr** [comment]
Bumping this to address a part of the original issue @KeeJef:

> so i can cosign any releases which go out

I don't think it's possible right now. While there are plans to allow self-publishing to Flathub (AFAIK), it's not done yet.

The current workflow is very hands-off (Download latest deb from session-desktop, unpack it, install - Flathub bot checks for new releases, updates the urls & hashes and merges automatically - Builds are being done on Flathub's infrastructure) but due to the nature of session, I'd find it reasonable if you'd want to take over the whole process. I'd suggest going the f-droid route and host your own repo (I'm aware of https://github.com/andyholmes/flatter for static hosting on GH pages with signing support etc). If you create your own repo, let us know and we'll mark this as EOL.

Otherwise, as barthalion said, you can only "verify" that the flatpak is official through DNS (which would also require for this package to be marked as EOL for the new app ID, from `network.loki.Session` to `io.oxen.Session`)

**Comment by KeeJef** [comment]
I don't seem to have write access to this repo currently , am i understanding correctly that i need to verify the app on flathub.org to get that access? And to verify ownership of the app i need to do domain verification on the loki.network domain?

**Comment by GeopJr** [comment]
The master branch is (or at least should be) protected. You can make a PR instead and merge it after it builds successfully.

I can't verify your repo access, only org members can, but since barthalion confirmed it, you should be able to create branches, merge PRs and close issues.

Verification only adds a checkmark next to the publisher, marking the flatpak as "Official". To verify an app you need to have access to the domain used in the app id, which in session's case is loki.network.

**Comment by KeeJef** [comment]
Ah yes i see, ill close this, looks like i already have the correct permissions

**Comment by 924nf9sh33nf** [comment]
@KeeJef 

Hi guys! this was closed, but session is not verified on flathub. 

https://flathub.org/apps/network.loki.Session

**Comment by KeeJef** [comment]
I have now verified ownership over that domain
